"""Helper: test_nikkei225_fetcher.py を生成するスクリプト"""
import pathlib

CONTENT = (
    '"""\n'
    "Nikkei225Fetcher unit tests\n"
    '"""\n'
    "import pytest\n"
    "import pandas as pd\n"
    "from pathlib import Path\n"
    "from src.low_hunter.nikkei225_fetcher import Nikkei225Fetcher\n"
    "\n\n"
    "@pytest.fixture\n"
    "def tmp_project(tmp_path):\n"
    "    cache_dir = tmp_path / 'data'\n"
    "    cache_dir.mkdir()\n"
    "    return tmp_path, cache_dir\n"
    "\n\n"
    "def _create_csv(path, rows, encoding='cp932'):\n"
    "    lines = [','.join(row) for row in rows]\n"
    "    path.write_text(chr(10).join(lines), encoding=encoding)\n"
    "\n\n"
    "def _gen_225(header=None):\n"
    "    header = header or ['\u92d8\u67c4\u30b3\u30fc\u30c9', '\u92d8\u67c4\u540d', '\u696d\u7a2e']\n"
    "    rows = [header]\n"
    "    for i in range(225):\n"
    "        rows.append([str(1000 + i), f'\u30c6\u30b9\u30c8\u92d8\u67c4{i}', '\u696d\u7a2e'])\n"
    "    return rows\n"
    "\n\n"
    "class TestLoadManualCsv:\n"
    "    def test_cp932(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', _gen_225(), 'cp932')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert len(result) == 225\n"
    "        assert result[0] == ('1000', '\u30c6\u30b9\u30c8\u92d8\u67c40')\n"
    "\n"
    "    def test_utf8(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', _gen_225(), 'utf-8')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert len(result) == 225\n"
    "\n"
    "    def test_utf8_sig(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', _gen_225(), 'utf-8-sig')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert len(result) == 225\n"
    "\n\n"
    "class TestColumnMapping:\n"
    "    def test_alt_columns(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', _gen_225(['\u30b3\u30fc\u30c9', '\u92d8\u67c4', '\u696d\u7a2e']), 'cp932')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert len(result) == 225\n"
    "\n"
    "    def test_unknown_columns_raises(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', _gen_225(['x', 'y', 'z']), 'cp932')\n"
    "        with pytest.raises(RuntimeError):\n"
    "            Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "\n\n"
    "class TestFallback:\n"
    "    def test_no_csv_uses_cache(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        rows = [(str(5000 + i), f'C{i}') for i in range(225)]\n"
    "        df = pd.DataFrame(rows, columns=['code', 'name'])\n"
    "        df.to_csv(cache / 'nikkei225_cache.csv', index=False, encoding='utf-8-sig')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert len(result) == 225\n"
    "\n"
    "    def test_nothing_raises(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        with pytest.raises(RuntimeError):\n"
    "            Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "\n\n"
    "class TestSafetyGuard:\n"
    "    def test_too_few_stocks(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        header = ['\u92d8\u67c4\u30b3\u30fc\u30c9', '\u92d8\u67c4\u540d', '\u696d\u7a2e']\n"
    "        rows = [header] + [[str(i), f'S{i}', 'X'] for i in range(50)]\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', rows, 'cp932')\n"
    "        with pytest.raises(RuntimeError):\n"
    "            Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "\n\n"
    "class TestCacheSaveLoad:\n"
    "    def test_cache_created(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', _gen_225(), 'cp932')\n"
    "        Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert (cache / 'nikkei225_cache.csv').exists()\n"
    "        df = pd.read_csv(cache / 'nikkei225_cache.csv', dtype=str)\n"
    "        assert len(df) == 225\n"
    "\n\n"
    "class TestCodeNormalization:\n"
    "    def test_float_code(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        header = ['\u92d8\u67c4\u30b3\u30fc\u30c9', '\u92d8\u67c4\u540d', '\u696d\u7a2e']\n"
    "        rows = [header] + [[f'{6000+i}.0', f'F{i}', 'D'] for i in range(225)]\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', rows, 'utf-8')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert result[0][0] == '6000'\n"
    "\n"
    "    def test_alpha_suffix(self, tmp_project):\n"
    "        root, cache = tmp_project\n"
    "        header = ['\u92d8\u67c4\u30b3\u30fc\u30c9', '\u92d8\u67c4\u540d', '\u696d\u7a2e']\n"
    "        rows = [header] + [[str(7000+i), f'N{i}', 'E'] for i in range(224)]\n"
    "        rows.append(['123A', 'Alpha', 'E'])\n"
    "        _create_csv(root / '\u65e5\u7d4c\u5e73\u5747225\u69cb\u6210\u92d8\u67c4.csv', rows, 'utf-8')\n"
    "        result = Nikkei225Fetcher(str(root), str(cache)).fetch()\n"
    "        assert '123A' in [r[0] for r in result]\n"
)

target = pathlib.Path("tests/unit/test_nikkei225_fetcher.py")
target.write_text(CONTENT, encoding="utf-8")
print(f"Written {len(CONTENT)} chars to {target}")
